Repository yooneverse/ssafystudy, pull requests merged in 2025-10, with the labels that each got.

#41 BAEK_1245_농장_관리_외_2문제_도현
  dohyun/week6/BAEK_12865_평범한_배낭.py
  dohyun/week7/BAEK_1245_농장_관리.py
  dohyun/week7/BAEK_2206_벽_부수고_이동하기.py
Labels: Queue, BFS, BAEKJOON

#42 BAEK_12904_A와_B_외_3문제_도현
  dohyun/week8/BAEK_1197_최소_스패닝_트리.py
  dohyun/week8/BAEK_12904_A와_B.py
  dohyun/week8/BAEK_14938_서강그라운드.py
  dohyun/week8/BAEK_1753_최단_경로.py
Labels: 그리디, BAEKJOON, Dijkstra, MST

#37 BAEK_1931_회의실_배정_승철
  seungcheol/week4/BEAK_1991_트리순회.py
  seungcheol/week4/SWEA_25052_등산로.py
  seungcheol/week5/BAEK_11060_점프점프.py
  seungcheol/week5/BAEK_1520_내리막길.py
  seungcheol/week5/BAEK_17070_파이프옮기기1.py
  seungcheol/week5/BAEK_17478_재귀함수가뭔가요.py
  seungcheol/week5/BAEK_1931_회의실배정.py
  seungcheol/week5/BAEK_2606_바이러스.py
  seungcheol/week6/BAEK_11399_ATM.py
  seungcheol/week6/BAEK_12865_평범한_배낭.py
  seungcheol/week6/BAEK_15683_감시.py
  seungcheol/week6/BAEK_17406_배열_돌리기_4.py
  seungcheol/week6/BAEK_1937_욕심쟁이_판다.py
  seungcheol/week6/BAEK_9358_순열_접기_게임.py
Labels: Backtracking, DFS, DP, 그리디, BAEKJOON
